[package]
name = "chattervan"
version = "0.1.0"
authors = ["Jonathan Dahan <hi@jonathan.is>"]
edition = "2018"

[dependencies]
ed25519-dalek = { git = "https://github.com/spebern/ed25519-dalek" }
rand = "0.6.4"
sha2 = "0.8.0"
base64 = "0.10.0"
